/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Scanner;

public class App {

    public static void main(String[] args) throws FileNotFoundException {
        Gson gson = new Gson();

        Scanner reader = new Scanner(new File("src/main/resources/recentquotes.JSON"));
        String quotes = "";
        while(reader.hasNextLine()){
            quotes+= reader.nextLine();
        }
//        System.out.println(quotes);
        Quote[] allQuotes = new Gson().fromJson(quotes, Quote[].class);
        for (int i = 0; i <allQuotes.length; i++) {
            System.out.println(allQuotes[i]);
        }

    }
}
